//Each new term in the **Fibonacci sequence** is generated by adding the previous two terms. 
//By starting with **1** and **2**, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...**
/*
Notice the pattern:
- 1 + 2 = 3
- 2 + 3 = 5
- 3 + 5 = 8
- 5 + 8 = 13
- And so on...
*/
//By considering the terms in the Fibonacci sequence whose values do not exceed **four million**,
//find the sum of the **even-valued** terms
public class Euler2 {
    
    public static void main(String[] args) {
    long start = System.nanoTime();
    int num1 = 1;
    int num2 = 1;
    int tsum = 0;
    int sum = 0;

        while(num2 <= 4000000) {
            if (num2%2==0){
            tsum += num2;
            }
            sum = num2+num1;
            num1=num2;
            num2=sum;
        }
        System.out.println("tsum:" + tsum);
        long stop = System.nanoTime();
        long durationNano = stop - start;
        double durationMilli = (double) durationNano / 1_000_000.0;
        System.out.println("Execution time: " + durationMilli);
    }
}