//Each new term in the **Fibonacci sequence** is generated by adding the previous two terms. 
//By starting with **1** and **2**, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...**
/*
Notice the pattern:
- 1 + 2 = 3
- 2 + 3 = 5
- 3 + 5 = 8
- 5 + 8 = 13
- And so on...
*/
//By considering the terms in the Fibonacci sequence whose values do not exceed **four million**,
//find the sum of the **even-valued** terms
public class OptEuler2 {
    
    public static void main(String[] args) {
    int num1 = 0;
    int num2 = 2;
    int tsum = 0;
    int sum = 0;
    int term = 1;

        while(num2 <= 4000000) {
            tsum += num2;
            System.out.println("num1:" + num1);
            System.out.println("num2:" + num2);
            System.out.println("tsum:" + tsum);
            System.out.println("term:"+term);
            System.out.println("===================");
            sum = num2*4+num1;
            num1=num2;
            num2=sum;
            term++;
        }

    }
}
